name: eliud_core
description: Eliud core

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  #flutter: ">=1.17.0 <2.0.0"

dependencies:
  bloc: 6.1.1
  flutter_bloc: 6.1.2
  #firebase_crashlytics: ^0.4.0+1
  #firebase_messaging: ^7.0.3
  firebase_core: 1.0.1
  firebase_auth: 1.0.1
  google_sign_in: 5.0.0
  google_sign_in_web: 0.10.0
  #flutter_widget_from_html: 0.5.2
  firebase_storage: 8.0.0
  google_fonts: 2.0.0
  #image: 2.1.19
  cloud_firestore: 1.0.1
  datetime_picker_formfield: ^1.0.0
  expandable: 4.1.2
  flutter_colorpicker: 0.3.5
  flutter_iconpicker: 2.2.3
  image_cropper: 1.2.1
  image_picker: 0.6.3+4
  equatable: 2.0.0
  #equatable: ^1.1.1
  delayed_display: 1.1.0
  transparent_image: 1.0.0
  camera: 0.8.0
  thumbnails: 1.0.1
  video_player: 1.0.1
  uuid: 3.0.1
  image: 3.0.1
  flutter_markdown: ^0.3.3
  cloud_functions: 1.0.0
  #flutter_widget_from_html_core: 0.5.2+1
  native_pdf_view: 4.0.1
  path: 1.8.0

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: "1.11.5"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true
