name: eliud_core
description: Eliud core

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  bloc: ^8.0.3
  cloud_firestore: 3.4.5
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  cloud_functions: 3.3.6
  datetime_picker_formfield: ^2.0.0
  delayed_display: ^2.0.0
  equatable: ^2.0.3
  expandable: ^5.0.1
  fast_image_resizer: 0.0.2
  firebase_storage: 10.3.0
  flutter_bloc: ^8.0.1
  flutter_circular_text: 0.3.1
  flutter_colorful_tab: 0.1.0
  flutter_colorpicker: 1.0.3
  flutter_markdown: ^0.6.6
  flutter_signin_button: 2.0.0
  google_fonts: ^3.0.1
  google_sign_in_web: ^0.10.0+3
  google_sign_in: ^5.1.0
  http: ^0.13.0
  image_picker: 0.8.5+3
  image: ^3.0.4
  path: ^1.8.0
  pdfx: 2.2.0
  photo_view: ^0.14.0
  sign_in_with_apple: 4.1.0
  transparent_image: ^2.0.0
  tuple: ^2.0.0
  uuid: ^3.0.4
  video_player: ^2.2.4
  video_thumbnail: 0.5.2
  pointer_interceptor: 0.9.3+3
  another_flushbar: 1.12.29

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: "1.11.5"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true

  assets:
    - packages/eliud_core/assets/undraw_co/undraw_online_video_ivvq.png
    - assets/images/avatar.png
    - assets/images/denied.png
