---
name: eliud_core
description: Eliud core is the core eliud package. It's a required package for all
  eliud apps. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_core
version: 1.2.0
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  equatable: ^2.0.5                                                                                  # ANDROID IOS LINUX MACOS WEB WINDOWS
  another_flushbar: ^1.12.30                                                                         # ANDROID IOS LINUX MACOS WEB WINDOWS
  flutter_signin_button: ^2.0.0                                                                      # ANDROID IOS LINUX MACOS WEB WINDOWS
  cloud_functions: ^4.5.8                                                                            # ANDROID IOS       MACOS WEB
  path_provider: ^2.1.1                                                                              # ANDROID IOS LINUX MACOS WEB WINDOWS

  eliud_core_model:                                                                                  # ANDROID IOS             WEB
    path: ../eliud_core_model
  eliud_core_main:                                                                                   # ANDROID IOS             WEB
    path: ../eliud_core_main
  eliud_core_helpers:                                                                                # ANDROID IOS             WEB
    path: ../eliud_core_helpers

  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
  - packages/eliud_core/assets/undraw_co/undraw_online_video_ivvq.png
  - assets/images/avatar.png
  - assets/images/denied.png
