name: eliud_core
description: Eliud core

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  bloc: 6.1.1
  flutter_bloc: 6.1.2
  #firebase_crashlytics: ^0.4.0+1
  #firebase_messaging: ^7.0.3
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  google_sign_in: 4.5.9
  google_sign_in_web: ^0.9.1
  flutter_widget_from_html: 0.5.2
  firebase_storage: ^7.0.0
  google_fonts: 1.1.0
  #image: 2.1.19
  cloud_firestore: ^0.16.0
  datetime_picker_formfield: ^1.0.0
  expandable: 4.1.2
  flutter_colorpicker: any
  flutter_iconpicker: any
  image_cropper: 1.2.1
  image_picker: 0.6.3+4
  equatable: ^1.1.1
  delayed_display: 1.1.0
  transparent_image: 1.0.0
  camera: ^0.7.0+2
  thumbnails: 1.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: "1.10.2"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true
