name: eliud_core
description: Eliud core

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  #flutter: ">=1.17.0 <2.0.0"

dependencies:
  bloc: ^7.1.0
  flutter_bloc: ^7.0.1
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.1
  google_sign_in: ^5.1.0
  google_sign_in_web: ^0.10.0+3
  firebase_storage: ^10.0.3
  google_fonts: ^2.1.0
  cloud_firestore: 2.5.3
  datetime_picker_formfield: ^2.0.0
  expandable: ^5.0.1
  flutter_colorpicker: ^0.6.0
  flutter_iconpicker: ^3.0.4
  image_picker: ^0.7.4
  equatable: ^2.0.3
  delayed_display: ^2.0.0
  transparent_image: ^2.0.0
  video_player: ^2.2.4
  uuid: ^3.0.4
  image: ^3.0.4
  flutter_markdown: ^0.6.6
  cloud_functions: 3.0.3
  native_pdf_renderer: ^3.1.0
  path: ^1.8.0
  pdf_render: ^1.0.12
  photo_view: ^0.12.0
  video_thumbnail: 0.4.3
  flutter_colorful_tab: 0.1.0
  flutter_circular_text: 0.3.1
  tuple: ^2.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: "1.11.5"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true

  assets:
    - packages/eliud_core/assets/undraw_co/undraw_online_video_ivvq.png
    - assets/images/avatar.png
