name: eliud_core
description: Eliud core

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  bloc: ^5.0.1
  flutter_bloc: ^5.0.1
  firebase_auth: 0.15.5+3
  google_sign_in: 4.4.3
  google_sign_in_web: ^0.9.1
  flutter_widget_from_html: 0.3.2+1		#DO NOT UPGRADE
  firebase_storage: ^3.1.5
  google_fonts: 1.1.0
  image: 2.1.12
  cloud_firestore: ^0.13.4+2
  datetime_picker_formfield: ^1.0.0
  expandable: 4.1.2
  flutter_colorpicker: any
  flutter_iconpicker: any
  image_cropper: 1.2.1
  image_picker: 0.6.3+4
  equatable: ^1.1.1

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: "1.10.2"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true

  assets:
    - assets/logo/

  fonts:
    - family: Tahu!
      fonts:
        - asset: assets/fonts/Tahu!.ttf
